In [32]:
import pandas as pd
from pyvis.network import Network
import networkx as nx
from IPython.display import HTML

In [33]:
df = pd.read_csv('synthetic_data.csv')
df.head()

,ts,uid,synth_src_ip,src_port,synth_dest_ip,dest_port,proto,service,duration,orig_bytes,...,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents,orig_mac,resp_mac
0,1.696677e+09,CrOwKi4m4j7TduMCEi,169.228.0.0,57550,127.0.0.200,53,udp,dns,0.001413,43,...,T,0,Dd,1,71,2,270,(empty),-,-
1,1.696678e+09,CiR0D53r6d7EpKJC17,132.239.0.200,61250,172.16.1.244,7000,tcp,-,2.003713,0,...,T,0,S,4,256,0,0,(empty),-,-
2,1.696678e+09,CJmsBd12kiY9BRnSi8,127.0.1.244,60872,192.168.1.244,53,udp,dns,0.000224,34,...,T,0,Dd,1,62,2,228,(empty),-,-
3,1.696677e+09,CF3ugp1tyx18akKCE8,100.64.0.200,50466,192.168.1.244,7000,tcp,-,4.110951,0,...,T,0,S,10,640,0,0,(empty),-,-
4,1.696678e+09,CwdeEK3IQhUNPi8Nwh,0.0.1.244,51127,192.135.238.10,53,tcp,dns,0.005200,36,...,T,0,ShADadFf,6,288,10,596,(empty),-,-

In [34]:
relevant_properties = ['synth_src_ip', 'synth_dest_ip', 'conn_state', 'orig_bytes']
df_relevant = df[relevant_properties]
df_relevant.head()

    synth_src_ip   synth_dest_ip conn_state orig_bytes
0    169.228.0.0     127.0.0.200         SF         43
1  132.239.0.200    172.16.1.244         S0          0
2    127.0.1.244   192.168.1.244         SF         34
3   100.64.0.200   192.168.1.244         S0          0
4      0.0.1.244  192.135.238.10         SF         36

In [40]:
nodes = pd.concat([df_relevant['synth_src_ip'], df_relevant['synth_dest_ip']]).unique().tolist()
graph_visual = Network(notebook=True, cdn_resources='remote')
graph_visual.add_nodes(nodes)
graph_visual.save_graph('connection_visual.html')
#HTML(filename="connection_visual.html")